mongo:
  client:
    port: ~
  database:
    name: "corobiapolitici"
    collections:
      raw: "raw"
      parsed: "parsed" 

      
logging:
  level: "INFO"
  filename: "corobiapolitici.log"

scrape:
  delay: 0.5

neo4j:
  client:
    uri: bolt://localhost:11001
    auth:
      - "neo4j"
      - "blabla"
  temp_csv: "C:/Users/dcsiba/Documents/temp_neo4j.csv"
  periodic_commit: 10000